### ISSUE TITLE
Click extension does not support a SVGAnimatedString href

### ISSUE THREAD

**Issue by bwells78** [adobe/reactor-extension-core#16]
Hello,

We have a React/D3 SPA that includes anchor tags embedded in SVGs. In one of our scenarios, the anchor's href attribute is of type SVGAnimatedString instead of the usual String.  

When Launch processes a click on these anchors, the browser is inadvertently reloaded because window.location is being set to a SVGAnimatedString object instead of a string- I believe [this is the spot](https://github.com/adobe/reactor-extension-core/blob/427f01bacbf781ee99d4e142b62370f2333ed717/src/lib/events/click.js#L100).

Is it possible to check for this scenario and switch to using href.baseVal when SVGAnimatedString is found?

Many thanks,
Ben

**Comment by jbarchibald** [comment]
@bwells78  thanks for reporting this issue.   We have documented it and will triage the issue.

This would be a great enhancement.  I may reach out to you for help validating once we have a solution.

**Comment by bwells78** [comment]
@jbarchibald That's great to hear, thanks so much! Happy to help when the time is right.

**Comment by thebenrob** [comment]
@adobe export issue to Jira project PDCL as Story

**Comment by brenthosie** [comment]
We're ready to look at this, can you set up a broken example for us to look at?

**Comment by bwells78** [comment]
Hi @brenthosie, sorry for delay- I've got a quick broken demo put together, just need to get okay from my team to expose the page on our site, back to you shortly.

**Comment by bwells78** [comment]
[This page](https://www.researchaffiliates.com/utilities/test-launch-svg) has giant SVG button that embeds its anchor link inside it.  One of our launch rules listens for clicks on elements with the class `ra-button-link` and attempts to execute when it's clicked- but you'll see that execution fail to complete because of this issue.  Let me know if I can help further, thanks so much-

**Comment by brenthosie** [comment]
@bwells78 Can you sign up for our Launch Developers slack group so we can chat some more?

https://bit.ly/3AQjUGp

**Comment by brenthosie** [comment]
@bwells78 Will you be able to join the Slack channel and talk to me before the end of the week?

**Comment by bwells78** [comment]
Brent and I just spoke and decided this is a corner case that doesn't necessarily need resolution, at least for our specific needs at this time.  Although I do see an JS error appear in the demo page above when clicking on the `<a>` embedded in a `<svg>`, we've successfully worked around this in the production app where this was first noticed some time ago.  I'll be back in touch if we see anything else we should reconnect about.  Many thanks, Brent & team- appreciate you taking a look for us.
