### ISSUE TITLE
localStorage/sessionStorage disabled causes some conditions to fail

### ISSUE THREAD

**Issue by arobsco** [adobe/reactor-extension-core#29]
When using conditions like max frequency, if the users browser has storage apis disabled then the condition fails as not met.

Ideally there would be an option within the condition configuration that asks me how i want to handle storage apis being unavailable (still fire the rule or don't fire the rule) or fallback to cookies.

### Expected Behaviour
Condition should fire with storage apis disabled

### Actual Behaviour
Condition doesn't fire with storage apis disabled

#### Steps to Reproduce
Create a condition which involves use of storage APIs

#### Platform and Version
Core 1.8.3

#### Sample Code that illustrates the problem
Max Frequency - once per pageview

**Comment by thebenrob** [comment]
It seems like having localStorage disabled would be an extreme edge case?  Can you describe more about the conditions in which an end-user would not have this enabled?

**Comment by arobsco** [comment]
We are seeing it on android app web views and private browsing mostly

**Comment by thebenrob** [comment]
Based on our our understanding, you should still have access to localStorage in both of those scenarios.  We're trying to understand if this is a real-world scenario, or something specific to your development environment.  Can you give us some steps to reproduce this?

**Comment by arobsco** [comment]
By default a webpage displayed within an android app has storage set to disabled (https://developer.android.com/reference/android/webkit/WebSettings#setDomStorageEnabled(boolean))

If you you launch within this webpage and make reference to the storage api then it will fail

**Comment by thebenrob** [comment]
@adobe export issue to Jira project PDCL

**Comment by thebenrob** [comment]
This applies to Max Frequency, Sampling, and Visitor Frequency.

**Comment by brenthosie** [comment]
Apologies that this sat around for so long. I'd like to discuss if this is still a concern since our code that tries to pull from `localStorage` and `sessionStorage` are wrapped in try/catch and return `null` during get and `false` during set.:

https://github.com/adobe/reactor-extension-core/blob/master/src/lib/helpers/getNamespacedStorage.js#L28-L48

**Comment by jeffreywalter** [comment]
@arobsco Do you have some time to provide a failing use case?

**Comment by brenthosie** [comment]
@arobsco If this ends up still being a problem then will you open an issue again? Thank you!
