### ISSUE TITLE
BUG: Direct Call Event should have trigger specific syntheticEvent

### ISSUE THREAD

**Issue by PrateekTikku** [adobe/reactor-extension-core#35]
### Expected Behaviour
Multiple rules triggering on the same direct call event (i.e. having the same direct call identifier) should have consistent values of event.$rule.name (syntheticEventMeta info) or any other information contained inside the syntheticEvent object.

### Actual Behaviour
Multiple rules triggering on the same direct call event (i.e. having the same direct call identifier), reference a common syntheticEvent object, causing incorrect information (especially syntheticEventMeta info) being accessed by the corresponding rule components which run asynchronously.

#### Steps to Reproduce
1) Create 2 direct call rules with the same identifier
2) Add an action to both rules which runs asynchronously e.g. Adobe Analytics set variables action
3) Trigger the direct call rule by calling _satellite.track function on the website
4) Try to access event.$rule.name inside the async rule action e.g. in custom code of Adobe Analytics set variables action
5) The value of event.$rule.name inside both the actions will be the name of rule 2, the one which triggers later

#### Platform and Version
Reproduced using core extension v1.8.4

**Comment by Aaronius** [comment]
@thebenrob, this one has some history behind it. Internally at Adobe, this is tracked as https://jira.corp.adobe.com/browse/DTM-14142 . We made an attempt at fixing it in March of 2020 (https://github.com/adobe/reactor-turbine/pull/100) but it caused problems in production (described in the JIRA issue I linked) and we had to roll it back.

**Comment by thebenrob** [comment]
✅ Jira issue PDCL-5144 is successfully created for this GitHub issue.

**Comment by brenthosie** [comment]
Being handled [within Turbine](https://github.com/adobe/reactor-turbine/pull/128).
