### ISSUE TITLE
Scripts won't run on Windows

### ISSUE THREAD

**Issue by frederikwerner** [adobe/reactor-extension-core#49]
I am trying to contribute to the Core Extension. Since I am a Windows user, I have a very mixed experience running the provided scripts. Specifically, I've run into those issues so far:
- Regarding the Sandbox, which I managed to get running eventually:The webpack.config.js config file contains paths like https://github.com/adobe/reactor-extension-core/blob/ac83ca7c6a7cbbd575477cf79c75738654fe626c/webpack.config.js#L110, https://github.com/adobe/reactor-extension-core/blob/ac83ca7c6a7cbbd575477cf79c75738654fe626c/webpack.config.js#L128, and https://github.com/adobe/reactor-extension-core/blob/ac83ca7c6a7cbbd575477cf79c75738654fe626c/webpack.config.js#L80, which contain the wrong type of slashes to run under windows. This causes a ton of error messages to appear and prevents the Sandbox from starting.
- Both the Linter and Tests also won't run. I haven't managed to get those running as of now.
- Probably other scripts are affected as well, but I haven't yet got to try those.

### Expected Behaviour
Running `npm run sandbox`, `npm run lint`, `npm run test` start the sandbox, linter, or tests and return a result.

### Actual Behaviour
A ton of errors showing up and the scripts fail.

### Reproduce Scenario (including but not limited to)
Follow installation instructions on https://github.com/adobe/reactor-extension-core#readme running Windows.

#### Steps to Reproduce
Run any of the mentioned scripts on windows

#### Platform and Version
Windows 10

**Comment by thebenrob** [comment]
This is all fair and true, but we have chosen not to prioritize running the open-source tools on a Windows machine.  They all run on Macs and all the various flavors of *nix.  If a Windows machine is all you have access too, I'd suggest looking into the Windows Subsystem for Linux (https://docs.microsoft.com/en-us/windows/wsl/install-win10).

**Comment by frederikwerner** [comment]
Oh, really? That comes as a total surprise to me. I would have expected a note in the readme pointing towards this decision, which would have saved me a weekend of trying to get things to run.
