### ISSUE TITLE
Feature request: Reduce need for Custom Code through additional Data Elements

### ISSUE THREAD

**Issue by frederikwerner** [adobe/reactor-extension-core#51]
### Expected Behaviour
Launch should provide a way to build web properties in a sustainable manner and give easy access to basic functionality that almost every website needs through a friendly user interface. Those operations should be supported out-of-the-box without the need for error prone customization. 

### Actual Behaviour
When using Launch, we need to heavily rely on Custom Code Data Elements for a lot of simple things. Those include:

1. Gathering information about the Visitor, like their Operating System, Device Type, Browser- and Window Size, which are already available as conditions in rules but not as Data Elements.
2. Conditional values like simple "If... Then... Else..." rules, which return one or the other value based on a comparison. Currently comparisons are only possible in conditions for rules, but not for Data Elements.
3. Routine JavaScript operations like getting a substring from a string, replacing strings, matching regex, handling arrays, getting the current time, etc. 

That brings all the potential issues of Custom Code (like additional files loading, errors, maintenance) and forces us to work in an unsustainable fashion. For example, I recently inherited a Launch property where >75% of the ~300 rules contained some form of custom code, which is basically unmaintainable in the long run.

The only way around this is for customers to create the above functionality in custom extensions, which puts the pressure of development and maintenance on the client and leads to a lot of basically identical private extensions without the potential for synergies.

I would be happy to help in creating those new Data Elements and have created https://github.com/frederikwerner/reactor-extension-core/tree/New-Data-Elements as a proposal of how things could look like.

### Reproduce Scenario (including but not limited to)
N/A

#### Steps to Reproduce
N/A

#### Platform and Version
All

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
N/A

**Comment by thebenrob** [comment]
@adobe export issue to Jira project PDCL as Story

**Comment by dompuiu** [comment]
We released the new data elements on v3.1.0.
