### ISSUE TITLE
`event` is undefined at runtime within the custom code data element type

### ISSUE THREAD

**Issue by stewartschillingsdi** [adobe/reactor-extension-core#6]
### Expected Behaviour
`event` will be available for inspection at runtime for custom code data elements.

### Actual Behaviour
`event` is not passed into custom code data elements at runtime. 
evaluating `event` from within custom code returns `undefined`

### Reproduce Scenario (including but not limited to)
In Launch, Create a Core > Custom Code data element named `foo` with the following code: 

> console.log('event is ', event);
> return 1

In Launch, Create a Direct Call rule with a trigger string of `test_foo`.  Add a condition to the rule of type `Value Comparison` using %foo% as the lhs and 'bar' as the rhs. 

Build this rule and library and test by running `_satellite.track('test_foo', {'a':1, 'b': 2})`
You will see a console message as the `foo` data element is resolved.  This message will say "event is undefined"

#### Steps to Reproduce
See above
#### Platform and Version
Launch Core v1.6.2
#### Sample Code that illustrates the problem
See above
#### Logs taken while reproducing problem
See above

**Comment by Aaronius** [comment]
Merged and is planned to be published in Core's next release (date TBD).
