### ISSUE TITLE
Feature request: Use "Add another" option field everywhere

### ISSUE THREAD

**Issue by frederikwerner** [adobe/reactor-extension-core#67]
### Expected Behavior
Conditions in Rules are evaluated with an "and" condition between them. As there is currently no option to use an "or" condition instead, users often need to use Custom Code to evaluate against dictionaries of elements, use the Mapping Table extension with added Data Elements, or even duplicate Rules. At least this is true for most conditions.

While most conditions only have one value to compare against, a handful (and coincidentally my favorite) conditions have an awesome solution to this already: The "Add another" button, as seen below
![image](https://user-images.githubusercontent.com/56084103/139707228-3e6c9ffd-9690-4ce4-b3e4-e154aa85d9b6.png)

This simple option solves this problem completely, but only on the few Condition Types that have it. I would expect this option to exist for pretty much any Condition Type that compares string values, but at least the Value Comparison Condition (and subsequently the Conditional Value Data Element).

### Actual Behavior
Lots of Custom Code, unnecessarily bloated libraries because of added extensions, or even duplicate content. And a lot of sad tag managers because of this!

Again, I would like to offer my help wherever I can, but this kind of React wizardry is beyond me.

### Reproduce Scenario (including but not limited to)
N/A

#### Steps to Reproduce
N/A

#### Platform and Version
N/A

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
N/A

**Comment by dompuiu** [comment]
I've checked the conditions. Some of them already have the `Add another` option. Others are providing the option to use regexes where you can mimic the OR functionality. In others it doesn't make sense. Can you be more specific and tell use where you see the need to the `Add Another` option? Adding it to all is not an option in my opinion.

**Comment by frederikwerner** [comment]
Sure! The ones where it immediately makes sense to me are these:
- Cookie
- Value Comparison (and Conditional Value Data Element) for everything except numeric and boolean comparison
- Variable
- Landing Page
- Traffic Source
- Query String Parameter
The regex option is enough for easy use cases but quickly becomes too long to manage. Take the Landing Page condition as an example, where an imaginary rule should fire if one of three possible URLs was the landing page. The regex for this case would be far too long for the field. But even with regex, this feature should be available for cases where more than one regex expression could match, making the individual regexes far easier to read.

**Comment by jeffreywalter** [comment]
@adobe export issue to Jira project PDCL as Story

**Comment by markhicken** [comment]
@adobe export issue to Jira project PDCL as Bug

**Comment by j0nv** [comment]
@frederikwerner we've move this up in our backlog. No ETA on delivery, but letting you know it's on our near-term radar.

**Comment by brenthosie** [comment]
This is in progress
