### ISSUE TITLE
Click Event's Link Delay Doesn't Support Data Elements

### ISSUE THREAD

**Issue by jeremy-harnois** [adobe/reactor-extension-core#9]
### Expected Behaviour

Set the link delay setting on the Click event with a data element.

### Actual Behaviour

Providing a data element in the link delay setting results in an error, and the event cannot be saved.

#### Steps to Reproduce

1. Create a new rule
2. Add a Click event from this extension
3. Check "if the element is a link, delay navigation"  
4. Manually enter a data element in the "Link delay" field
5. Click Keep Changes button

#### Platform and Version

Core Extension v1.6.2

#### Sample Code that illustrates the problem

![image](https://user-images.githubusercontent.com/24924335/69358820-7f8e3100-0c55-11ea-899c-caf324a38b1c.png)

**Comment by thebenrob** [comment]
Thanks for logging the issue.  I've added this to the backlog and we'll get it prioritized.

**Comment by brenthosie** [comment]
Resolved by #41
